CREATE TABLE revenues (
      revenue_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      revenue_date   DATE NOT NULL,
      revenue_amount DECIMAL(19, 2) NOT NULL
);

CREATE INDEX idx_revenues_revenue_date ON revenues (revenue_date);